### ISSUE TITLE
Coherence: tests and builds

### ISSUE THREAD

**Issue by kindermoumoute** [intelsdi-x/snap-plugin-collector-elasticsearch#15]
As a plugin developer, I want to run consistency tests and builds in all my Snap plugin repos:
1. Run the test with `make test-small`. 
2. Same with `make check`.
3. When building, I want my binary to go in `build/$OS/$ARCH/`.

NB:
[Influxdb plugin](https://github.com/intelsdi-x/snap-plugin-publisher-influxdb) has the most updated scripts. For this plugin:
`Makefile`
`scripts/test.sh` 
`scripts/deps.sh` 
`scripts/build.sh` 
`scripts/common.sh` 

EDIT: may need to change `.Travis.yml` too.

**Comment by candysmurf** [comment]
addressed by PR #18
